### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by gatoravi** [TwistingTwists/news-scraper#1]
Hi, 
Thanks for the nice work.
Could you add a license for this project?
Thanks,
Avi

**Comment by hargup** [comment]
@gatoravi good to hear that you liked the work and thanks for pointing out there is no license. @TwistingTwists has added the license at GPLv3.

**Comment by gatoravi** [comment]
Thanks guys, this is great!

**Comment by TwistingTwists** [comment]
@gatoravi  : Welcome. :)
